name: Deploy Dev to VPS

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script on Dev VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_ECOM_DEV_HOST }}
          username: ${{ secrets.VPS_ECOM_DEV_USER }}
          key: ${{ secrets.VPS_ECOM_DEV_SSH_KEY }}
          port: ${{ secrets.VPS_ECOM_DEV_PORT }}
          script: |
            cd /var/www/ecmmerce-backend-dev/Ecmmerce-Backend
            chmod +x ./.scripts/deploy-dev.sh
            ./.scripts/deploy-dev.sh
